server.port=8081
spring.datasource.url=jdbc:mariadb://192.168.1.233:3306/bustartdb
spring.datasource.username=bustart
spring.datasource.password=Test123
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.show-sql=true
spring.main.allow-circular-references=true

logging.level.org.springframework.security=INFO
