package com.bustart.main.bo;

import java.io.Serializable;
import java.util.Date;

/**
 * Business Object used to send customer data to external clients.
 * Includes the unique identifier generated by the database.
 * @author Slam245
 *
 */
public class CustomerOutputBO implements Serializable {

    private static final long serialVersionUID = 1L;

    private Long id;
    private String firstName;
    private String lastName;
    private String secondLastName;
    private String address;
    private String phoneNumber;
    private String email;
    private Boolean hasWhatsapp;
    private String userNameCreator;
	private Date creationDate;
	private String userNameLastModifier;
	private Date lastModifiedDate; 
	private Boolean statusCode;

    /**
     * Default constructor.
     */
    public CustomerOutputBO() {
    }

    // --- GETTERS AND SETTERS ---

    /**
     * @return The unique database identifier.
     */
    public Long getId() {
        return id;
    }

    /**
     * @param id The unique database identifier to set.
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * @return The customer's first name.
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * @param firstName The first name to set.
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * @return The customer's primary surname.
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * @param lastName The primary surname to set.
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * @return The customer's secondary surname (nullable).
     */
    public String getSecondLastName() {
        return secondLastName;
    }

    /**
     * @param secondLastName The secondary surname to set.
     */
    public void setSecondLastName(String secondLastName) {
        this.secondLastName = secondLastName;
    }

    /**
     * @return The customer's full address.
     */
    public String getAddress() {
        return address;
    }

    /**
     * @param address The address string to set.
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * @return The 10-digit phone number.
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * @param phoneNumber The 10-digit numeric phone number to set.
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * @return The customer's email address.
     */
    public String getEmail() {
        return email;
    }

    /**
     * @param email The email address to set.
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * @return True if the customer has WhatsApp.
     */
    public Boolean getHasWhatsapp() {
        return hasWhatsapp;
    }

    /**
     * @param hasWhatsapp The WhatsApp status to set.
     */
    public void setHasWhatsapp(Boolean hasWhatsapp) {
        this.hasWhatsapp = hasWhatsapp;
    }
    	/**
	 * @return the userNameCreator
	 */
	public String getUserNameCreator() {
		return userNameCreator;
	}
	/**
	 * @param userNameCreator the userNameCreator to set
	 */
	public void setUserNameCreator(String userNameCreator) {
		this.userNameCreator = userNameCreator;
	}
	/**
	 * @return the creationDate
	 */
	public Date getCreationDate() {
		return creationDate;
	}
	/**
	 * @param creationDate the creationDate to set
	 */
	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}
	/**
	 * @return the userNameLastModifier
	 */
	public String getUserNameLastModifier() {
		return userNameLastModifier;
	}
	/**
	 * @param userNameLastModifier the userNameLastModifier to set
	 */
	public void setUserNameLastModifier(String userNameLastModifier) {
		this.userNameLastModifier = userNameLastModifier;
	}
	/**
	 * @return the lastModifiedDate
	 */
	public Date getLastModifiedDate() {
		return lastModifiedDate;
	}
	/**
	 * @param lastModifiedDate the lastModifiedDate to set
	 */
	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}
	/**
	 * @return the statusCode
	 */
	public Boolean getStatusCode() {
		return statusCode;
	}
	/**
	 * @param statusCode the statusCode to set
	 */
	public void setStatusCode(Boolean statusCode) {
		this.statusCode = statusCode;
	}
}